name = "Alert"
uuid = "28312eec-4d86-447d-83ad-bc2b262de792"
authors = ["David Little <david.frank.little@gmail.com> and contributors"]
version = "0.1.2"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1"
